travis:
  secure:
    BINSTAR_TOKEN: wZN1dgCCfCOva+3xJswzzgB05Zxisou4CEXq42hmzzb4MN62Qz/SThp7EUFjes0H/65t4ThlS144kKAEMNyogod9Gn4BaCOblEAxQhnjkRfoJiBDvAloFNf7sfFjk/dqW7OZeYXtOD4lg7dU4qnbH3vBOFS+gCsMh5pfH70T08oD102A/GJQ3wmbFgGZlMwnDqxAZ4824r5tBmN2Y7i7fmzHHfnIArtWq0dv7OaUaXftqdbGEyZdk6KSCOPsI0La+iHiQ93hZMfIyQ6lLOzFjSin1IwgACLp7QFq98+K6BjNB/SdORMHZ5MNhJJ8LberxDgdo3wVyomqan91kIwU/ZwaY6l1pYqi7O5rTH0gEvmomEpSpLZRCBHQAMfd4HExnk6Q4ovilLJf3wF2DfFI++i8DmZ/EIcgT4n8uM/gFhcrt99HPoxbADXkJV3nAuHVA/XFmcMhVj/uYV0A1Y08O1as0kOhzmP5Gd2vIxRDuSQPDlyROLbCP8sXvS077qwYMvWnKZixzyhVZg+dvhYf3uht7gjXb+wocv0Uk86YTaVFHC+XGAIippDdrsnT+c19Gipzm9TNRW1JbqXaUoVKs22q95FbcFuuelY0rL/HQuVdsdXiEKv/9S1Gt3JR1pVWn+Fm1xlXEIkgZEWF3pKY+1JDKgrcFDG0u1KT7KBNrMw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
