travis:
  secure:
    BINSTAR_TOKEN: atcwaDFdmFPLAGN80UKc0oeMLKIm7Xo3vfqESbkHodN/V+J5yQX/A7RdYoIihD9xU3g99VHFg656L8uFpmyFEGrgyTJqEyJYOhG2K6jtjZaSG5+3ndj/uW1S6pd86gWsIHL+lfGCwaNnJmHxPfhPCLbTlD1n9NBT2KD6++ps3PGQMyuTVXwTyMirVcfHTv+/MxsYhDTKfsGkFsMcIvO54i4bW1OvAP5E3NP7EcxRyIR/KB2OTCbi8zDq4dT0Z0gIJ0SR+dP7/N2ztOIZ8Ai1D4GBbPnhO+OUH3Kz49oXwQGIKuS9lmEb8v0rq6yTqwqIGDA1/ESe13gmra/VtxUDp+wU0cIDeHBAsc4V7rcf5AgWeZO7XcjVMEJUOs213jSxKTgqktH0BD60RyCFqaXLvRSem21Q601cfQ4FR1pHWtnRj+k4zwP8ExQAPGhBGUqj9svIRtVe9shbLwwe8uOalW1lU8aK/5NXp3B1Umzed2QpmQZsFOJBWb3WI7Za9FwVDALFScPFBt+CBgmgM2W+tokP+xWQnlXPRPYqruT8PzhZ51SfXnCah6af0XKYdRW9T0YQd94EZvPcaGU7pOZ1HOP59SVajDE8wFzr1+4OZdsevtM4NQcqefkmU0v1AwTad2XJ5at+oUxOkyslCo7tEibnmGjDgyQI8jJ0FpLHqRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
